### ISSUE TITLE
error in switch plugin with a specific file

### ISSUE THREAD

**Issue by thefab** [metwork-framework/mfdata#101]
```
Traceback (most recent call last):
  File "/opt/metwork-mfdata-0.5/opt/python3/lib/python3.5/site-packages/acquisition-0.0.0-py3.5.egg/acquisition/step.py", line 119, in _exception_safe_call
    return func(*args, **kwargs)
  File "/home/mfdata/var/plugins/switch/main.py", line 161, in process
    system_magic = get_magic(xaf)
  File "/home/mfdata/var/plugins/switch/main.py", line 25, in get_magic
    tag_magic = magic.from_file(xaf_file.filepath)
  File "/home/mfdata/var/plugins/switch/local/lib/python3.5/site-packages/magic.py", line 92, in from_file
    return self._handle509Bug(e)
  File "/home/mfdata/var/plugins/switch/local/lib/python3.5/site-packages/magic.py", line 101, in _handle509Bug
    raise e
  File "/home/mfdata/var/plugins/switch/local/lib/python3.5/site-packages/magic.py", line 90, in from_file
    return maybe_decode(magic_file(self.cookie, filename))
  File "/home/mfdata/var/plugins/switch/local/lib/python3.5/site-packages/magic.py", line 247, in magic_file
    return _magic_file(cookie, coerce_filename(filename))
  File "/home/mfdata/var/plugins/switch/local/lib/python3.5/site-packages/magic.py", line 188, in errorcheck_null
    raise MagicException(err)
magic.MagicException: b'Macintosh HFS Extended version 9220 data (mounted) vasprintf failed (Invalid or incomplete multibyte or wide character)'
```

**Comment by thefab** [comment]
Corresponding tags in trash:

```
0.switch.main.enter_step = 2019-03-27T00:12:20:833991
0.switch.main.exit_step = 2019-03-27T00:12:20:835116
0.switch.main.process_status = nok
first.core.original_basename = LFPW33242935.b
first.core.original_dirname = transmet_fac
first.core.original_uid = 1aa1759427ef415baf2818fe629d8312
latest.core.step_counter = 0
```

**Comment by thefab** [comment]
file output:

```
$ file 8f6c48841a5841949a5d43dc145f7d20
8f6c48841a5841949a5d43dc145f7d20: ERROR: Macintosh HFS Extended version 9220 data (mounted) vasprintf failed (Invalid or incomplete multibyte or wide character)
$ echo $?
1
```
