### ISSUE TITLE
exception in xattrfile in some cases

### ISSUE THREAD

**Issue by thefab** [metwork-framework/mfdata#192]
```
Traceback (most recent call last):
  File "/home/mfdata/var/plugins/httpsend1/send.py", line 72, in <module>
    x.run()
  File "/opt/metwork-mfdata-0.8/opt/python3/lib/python3.7/site-packages/acquisition-0.0.0-py3.7.egg/acquisition/step.py", line 553, in run
    self.args.redis_unix_socket_path)
  File "/opt/metwork-mfdata-0.8/opt/python3/lib/python3.7/site-packages/acquisition-0.0.0-py3.7.egg/acquisition/step.py", line 326, in __run_in_daemon_mode
    self._process(xaf)
  File "/opt/metwork-mfdata-0.8/opt/python3/lib/python3.7/site-packages/acquisition-0.0.0-py3.7.egg/acquisition/step.py", line 142, in _process
    before_status = self._before(xaf)
  File "/opt/metwork-mfdata-0.8/opt/python3/lib/python3.7/site-packages/acquisition-0.0.0-py3.7.egg/acquisition/step.py", line 180, in _before
    xaf.rename(tmp_filepath)
  File "/opt/metwork-mfdata-0.8/opt/python3/lib/python3.7/site-packages/xattrfile-0.0.0-py3.7.egg/xattrfile/__init__.py", line 396, in rename
    pipe.execute()
  File "/opt/metwork-mfext-0.8/opt/python3/lib/python3.7/site-packages/redis/client.py", line 3520, in execute
    return execute(conn, stack, raise_on_error)
  File "/opt/metwork-mfext-0.8/opt/python3/lib/python3.7/site-packages/redis/client.py", line 3435, in _execute_transaction
    self.raise_first_error(commands, response)
  File "/opt/metwork-mfext-0.8/opt/python3/lib/python3.7/site-packages/redis/client.py", line 3469, in raise_first_error
    raise r
redis.exceptions.ResponseError: Command # 1 (RENAME xattr_d305527261a53d8960f73cd271abf9e0 xattr_bc05ce48b367664683d40c7f7dd49beb) of pipeline caused error: no such key
```

probably caused by a "old files garbage collection" and a big reinject delay

probably not really a bug but this exception should be catched in xattrfile

**Comment by thefab** [comment]
seems to be caused by a concurrency issue in hardlinking feature
